# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\archéo poincons\60_outil_poincons\license_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_licenseDialog(object):
    def setupUi(self, licenseDialog):
        licenseDialog.setObjectName("licenseDialog")
        licenseDialog.resize(990, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(licenseDialog.sizePolicy().hasHeightForWidth())
        licenseDialog.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(licenseDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 980, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.scrollArea = QtWidgets.QScrollArea(licenseDialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 961, 421))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 959, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(licenseDialog)
        self.buttonBox.rejected.connect(licenseDialog.close) # type: ignore
        self.buttonBox.accepted.connect(licenseDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(licenseDialog)

    def retranslateUi(self, licenseDialog):
        _translate = QtCore.QCoreApplication.translate
        licenseDialog.setWindowTitle(_translate("licenseDialog", "Licensing"))
        self.label.setText(_translate("licenseDialog", "INIT"))
