# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from translator import tr, current_language

class Ui_Loading(object):
    def setupUi(self, Loading):
        Loading.setObjectName("Loading")
        Loading.resize(400, 172)
        self.progressBar = QtWidgets.QProgressBar(Loading)
        self.progressBar.setGeometry(QtCore.QRect(30, 20, 351, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.loading_symbol = QtWidgets.QLabel(Loading)
        self.loading_symbol.setGeometry(QtCore.QRect(160, 60, 100, 100))
        self.loading_symbol.setMinimumSize(QtCore.QSize(100, 100))
        self.loading_symbol.setMaximumSize(QtCore.QSize(100, 100))
        self.loading_symbol.setText("")
        self.loading_symbol.setPixmap(QtGui.QPixmap("resources/media/empty.png"))
        self.loading_symbol.setScaledContents(True)
        self.loading_symbol.setObjectName("loading_symbol")

        self.retranslateUi(Loading)
        QtCore.QMetaObject.connectSlotsByName(Loading)

    def retranslateUi(self, Loading):
        _translate = QtCore.QCoreApplication.translate
        Loading.setWindowTitle(_translate("Loading", tr("pleaseWait")))
